Repository linode/docs, pull requests merged in 2018-02, with the labels that each got.

#1462 [New] Introduction to PySpark
  docs/development/java/install-java-8-ppa.md
  docs/development/python/install_python_miniconda.md
  docs/development/python/introduction-to-pyspark.md
Labels: Tech Edit

#1456 [NEW] Build nginx with pagespeed
  docs/assets/nginx-add-https-module.png
  docs/assets/nginx-finished-compiling-with-pagespeed.png
  docs/assets/nginx-from-source-installation-directories.png
  docs/web-servers/nginx/build-nginx-with-pagespeed-from-source.md
  docs/web-servers/nginx/install-nginx-pagespeed-module-on-ubuntu1604.md
  docs/web-servers/nginx/nginx-with-pagespeed-on-ubuntu-14-04.md
Labels: Tech Edit

#1411 [Update] Use kill and killall to terminate processes
  docs/assets/manage_processes_with_killall_and_kill.png
  docs/assets/use-killall-and-kill-commands-to-stop-processes-on-linux.png
  docs/quick-answers/linux/find-and-terminate-processes-from-the-linux-or-macos-command-line.md
  docs/tools-reference/tools/use-killall-and-kill-to-stop-processes-on-linux.md
  docs/tools-reference/tools/use-killall-and-kill-to-stop-processes.md
Labels: SEO Edit

#1466 Added note on keypair naming
  docs/security/authentication/use-public-key-authentication-with-ssh.md
Labels: enhancement

#1440 [NEW] Odoo 11 Cluster on Ubuntu
  ci/vale/dictionary.txt
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-11-backup-gui-01.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-11-backup-gui-02.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-11-backup-gui-error.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-11-create-db.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-11-login-screen.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-11-welcome.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-deployment-01.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-deployment-02.png
  docs/assets/install-an-odoo-11-stack-on-ubuntu-16-04-using-linode/odoo-deployment-03.png
  docs/websites/cms/install-an-odoo-11-stack-on-ubuntu-16-04.md
Labels: Copy Edit

#1524 [NEW] Manage a Docker Cluster with Kubernetes
  ci/vale/dictionary.txt
  docs/applications/containers/manage-a-docker-cluster-with-kubernetes.md
  docs/assets/manage-a-docker-cluster-with-kubernetes/kubernetes-cluster.png
  docs/assets/manage-a-docker-cluster-with-kubernetes/manage-a-docker-cluster-with-kubernetes.png
Labels: Freelancer
