Repository linode/docs, pull requests merged in 2020-07, with the labels that each got.

#3439 [New] Deploying Percona Monitoring and Management (PMM) with One-Click Apps
  docs/platform/one-click/how-to-deploy-percona-monitoring-management-with-one-click-apps/deploy-percona-one-click.png
  docs/platform/one-click/how-to-deploy-percona-monitoring-management-with-one-click-apps/index.md
  docs/platform/one-click/how-to-deploy-percona-monitoring-management-with-one-click-apps/perconafinal.png
  docs/platform/one-click/how-to-deploy-percona-monitoring-management-with-one-click-apps/perconahome.png
Labels: Do Not Merge

#3445 Update links for Cloud Manager
  docs/applications/cloud-storage/tahoe-lafs-on-debian-9/index.md
  docs/platform/api/_index.md
  docs/platform/api/api-key/index.md
  docs/platform/create-limited-developer-account/index.md
  docs/platform/disk-images/disk-images-and-configuration-profiles/index.md
  docs/platform/disk-images/migrating-a-server-to-your-linode/index.md
  docs/platform/longview/longview-app-for-mysql-classic/index.md
  docs/platform/longview/longview-app-for-nginx-classic/index.md
  docs/platform/manager/using-the-linode-shell-lish/index.md
  docs/quick-answers/linode-platform/enable-backups-on-a-linode/index.md
  docs/security/recovering-from-a-system-compromise/index.md
  docs/tools-reference/custom-kernels-distros/install-alpine-linux-on-your-linode/index.md
  docs/tools-reference/custom-kernels-distros/install-nixos-on-linode/index.md
  docs/tools-reference/introduction-to-linux-concepts/index.md
  docs/tools-reference/linux-system-administration-basics/index.md
  docs/troubleshooting/disaster-recovery-guide/index.md
  docs/troubleshooting/troubleshooting-basic-connection-issues/index.md
  docs/troubleshooting/troubleshooting/index.md
  docs/uptime/monitoring-and-maintaining-your-server/index.md
Labels: bug

#3460 How to deploy Jenkins X in LKE
  ci/vale/dictionary.txt
  docs/kubernetes/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/approve-pr.png
  docs/kubernetes/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/create-cluster.png
  docs/kubernetes/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/github-token.png
  docs/kubernetes/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/index.md
  docs/kubernetes/how-to-deploy-jenkins-x-in-linode-kubernetes-engine/learnk8s_jenkinsX.png
Labels: learn-k8s
