Repository linode/docs, pull requests merged in 2021-04, with the labels that each got.

#4040 Adding update for WordPress on Ubuntu 18.04 article.
  docs/guides/websites/cms/wordpress/install-wordpress-ubuntu-18-04/index.md
Labels: SEO Improvements

#4100 what is sqlite
  docs/guides/databases/sqlite/_index.md
  docs/guides/databases/sqlite/what-is-sqlite/Turner_sqlite.png
  docs/guides/databases/sqlite/what-is-sqlite/index.md
  resources/_gen/images/guides/databases/sqlite/what-is-sqlite/Turner_sqlite_hu240fe9425be52278670fb6dbb7ba44c3_69842_1729x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/databases/sqlite/what-is-sqlite/Turner_sqlite_hu240fe9425be52278670fb6dbb7ba44c3_69842_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/databases/sqlite/what-is-sqlite/Turner_sqlite_hu240fe9425be52278670fb6dbb7ba44c3_69842_640x400_fill_catmullrom_smart1_2.png
  resources/_gen/images/guides/databases/sqlite/what-is-sqlite/Turner_sqlite_hu240fe9425be52278670fb6dbb7ba44c3_69842_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: est-ext

#3779 VLANs Release
  ci/vale/dictionary.txt
  docs/guides/platform/vlan/_index.md
  docs/guides/platform/vlan/common-linode-vlan-use-cases/index.md
  docs/guides/platform/vlan/common-linode-vlan-use-cases/multi-vlan-config.png
  docs/guides/platform/vlan/common-linode-vlan-use-cases/nodebalancer-vlan-config.png
  docs/guides/platform/vlan/common-linode-vlan-use-cases/vlan-kubernetes-cluster-config.png
  docs/guides/platform/vlan/common-linode-vlan-use-cases/vlan-web-server-db-config.png
  docs/guides/platform/vlan/feature.svg
  docs/guides/platform/vlan/getting-started-with-vlans/create-new-linode.png
  docs/guides/platform/vlan/getting-started-with-vlans/edit-button-for-configuration-profile.png
  docs/guides/platform/vlan/getting-started-with-vlans/index.md
  docs/guides/platform/vlan/getting-started-with-vlans/network-interface-purpose.png
  docs/guides/platform/vlan/getting-started-with-vlans/reboot-linode.png
  docs/guides/platform/vlan/getting-started-with-vlans/vlan-new-linode.png
  docs/guides/platform/vlan/how-to-create-a-private-network-with-linode-vlans-api/index.md
  docs/products/networking/vlans/_index.md
  docs/products/networking/vlans/developers/index.md
  docs/products/networking/vlans/feature.svg
  docs/products/networking/vlans/get-started/index.md
  docs/products/networking/vlans/guides/_index.md
  docs/products/networking/vlans/guides/access-your-vlans-details/index.md
  docs/products/networking/vlans/guides/detach-a-linode-from-your-vlan/index.md
  docs/products/networking/vlans/guides/manually-configuring-a-vlan/index.md
  docs/products/networking/vlans/guides/vlans-beta-note-shortguide/index.md
  docs/products/networking/vlans/guides/vlans-limitations-shortguide/index.md
Labels: Do Not Merge

#4045 Understanding how TLS works
  docs/guides/security/ssl/what-is-a-tls-certificate/index.md
Labels: est-ext

#4055 Updated document for Modify file permissions with CHMOD guide
  docs/guides/tools-reference/tools/modify-file-permissions-with-chmod/index.md
Labels: SEO Improvements

#4185 Marketplace Add: Peppermint
  docs/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/index.md
  docs/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/peppermint.png
  docs/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/peppermint_settings.png
  resources/_gen/images/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/peppermint_huc824a77c6e67cacf7926fcee007b89a6_29377_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/peppermint_huc824a77c6e67cacf7926fcee007b89a6_29377_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/peppermint_huc824a77c6e67cacf7926fcee007b89a6_29377_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/peppermint_settings_hu6c55d70b5efbb87935d96be32045392c_43877_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-peppermint-with-marketplace-apps/peppermint_settings_hu6c55d70b5efbb87935d96be32045392c_43877_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: marketplace

#4174 Marketplace add: Ant Media Server
  ci/vale/dictionary.txt
  docs/guides/platform/marketplace/deploy-antmediaserver-with-marketplace-apps/antmediaserver.png
  docs/guides/platform/marketplace/deploy-antmediaserver-with-marketplace-apps/index.md
  resources/_gen/images/guides/platform/marketplace/deploy-antmediaserver-with-marketplace-apps/antmediaserver_hu1a3c8cbec20814fc6d9bb86df8a137fb_458851_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-antmediaserver-with-marketplace-apps/antmediaserver_hu1a3c8cbec20814fc6d9bb86df8a137fb_458851_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-antmediaserver-with-marketplace-apps/antmediaserver_hu1a3c8cbec20814fc6d9bb86df8a137fb_458851_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: marketplace

#4180 Marketplace add: Owncast
  ci/vale/dictionary.txt
  docs/guides/platform/marketplace/deploy-owncast-with-marketplace-apps/index.md
  docs/guides/platform/marketplace/deploy-owncast-with-marketplace-apps/owncast.png
  resources/_gen/images/guides/platform/marketplace/deploy-owncast-with-marketplace-apps/owncast_hu35e24dfb6b8e7cd82cf7e3453afb7bbe_147027_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-owncast-with-marketplace-apps/owncast_hu35e24dfb6b8e7cd82cf7e3453afb7bbe_147027_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-owncast-with-marketplace-apps/owncast_hu35e24dfb6b8e7cd82cf7e3453afb7bbe_147027_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: marketplace

#4233 How to use date in JavaScript.
  .gitignore
  docs/guides/development/javascript/how-to-use-date-in-javascript/index.md
  docs/guides/development/javascript/how-to-use-date-in-javascript/js-demo-compare-dates.png
  docs/guides/development/javascript/how-to-use-date-in-javascript/js-demo-get-full-year.png
  docs/guides/development/javascript/how-to-use-date-in-javascript/js-demo-new-date.png
  docs/guides/development/javascript/how-to-use-date-in-javascript/js-demo-set-year.png
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-compare-dates_huf6ca7406829fa46a65754d276d8a042b_124211_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-compare-dates_huf6ca7406829fa46a65754d276d8a042b_124211_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-compare-dates_huf6ca7406829fa46a65754d276d8a042b_124211_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-get-full-year_hue21ede7977302dc17cbbe28403aa2441_99264_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-get-full-year_hue21ede7977302dc17cbbe28403aa2441_99264_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-new-date_hu7d1b73e13a18a1a14509599a5f930000_72746_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-new-date_hu7d1b73e13a18a1a14509599a5f930000_72746_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-set-year_hu1d2ebc7986ddaabdeb9753e3723363bb_118032_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/development/javascript/how-to-use-date-in-javascript/js-demo-set-year_hu1d2ebc7986ddaabdeb9753e3723363bb_118032_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: SEO Improvements
