Repository linode/docs, pull requests merged in 2021-02, with the labels that each got.

#3959 [New] How to Use MySQL Views
  ci/vale/dictionary.txt
  docs/guides/databases/mysql/how-to-create-and-use-mysql-views/index.md
Labels: wfl

#3973 [New] How to Work with MySQL Subqueries
  ci/vale/dictionary.txt
  docs/guides/databases/mysql/how-to-work-with-mysql-subqueries/index.md
Labels: wfl

#3893 [Update] Manage Billing in Cloud Manager & Accounts and Passwords
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-amount-due-and-uninvoiced-balance.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-and-payment-history-table.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-change-card-small.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-change-card.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-current-balance-small.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-current-balance.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-edit-payment-method.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/billing-make-a-payment-panel.png
  docs/guides/platform/billing-and-support/manage-billing-in-cloud-manager/index.md
  docs/guides/platform/get-started/accounts-and-passwords/accounts-user-permissions-small.png
  docs/guides/platform/get-started/accounts-and-passwords/accounts-user-permissions.png
  docs/guides/platform/get-started/accounts-and-passwords/index.md
  docs/guides/platform/manager/accounts-add-users-shortguide/accounts-add-a-user-menu.png
  docs/guides/platform/manager/accounts-add-users-shortguide/accounts-overview-small.png
  docs/guides/platform/manager/accounts-add-users-shortguide/accounts-overview.png
  docs/guides/platform/manager/accounts-add-users-shortguide/index.md
  docs/guides/platform/manager/accounts-change-email-shortguide/accounts-my-profile-change-email-small.png
  docs/guides/platform/manager/accounts-change-email-shortguide/accounts-my-profile-change-email.png
  docs/guides/platform/manager/accounts-change-email-shortguide/accounts-select-my-profile.png
  docs/guides/platform/manager/accounts-change-email-shortguide/index.md
  docs/guides/platform/manager/accounts-change-username-shortguide/accounts-update-a-username.png
  docs/guides/platform/manager/accounts-change-username-shortguide/index.md
  docs/guides/platform/manager/accounts-remove-user-shortguide/index.md
  docs/guides/platform/manager/accounts-reset-root-password-shortguide/accounts-power-off-linode-small.png
  docs/guides/platform/manager/accounts-reset-root-password-shortguide/accounts-power-off-linode.png
  docs/guides/platform/manager/accounts-reset-root-password-shortguide/index.md
  docs/guides/platform/manager/accounts-update-contact-info-shortguide/accounts-update-billing-info-small.png
  docs/guides/platform/manager/accounts-update-contact-info-shortguide/accounts-update-billing-info.png
  docs/guides/platform/manager/accounts-update-contact-info-shortguide/index.md
  docs/guides/quick-answers/linode-platform/change-cloud-manager-password-shortguide/index.md
  docs/guides/quick-answers/linode-platform/reset-the-root-password-on-your-linode/index.md
  docs/guides/quick-answers/linode-platform/reset-the-root-password-on-your-linode/reset-password-power-down-linode.png
Labels: Cloud Manager UI Updates

#3983 [New] Installing Riot on Debian 10
  docs/guides/applications/messaging/installing-riot-on-debian-10/index.md
Labels: wfl

#3456 [New] Adds guide on securing logstash inputs.
  ci/vale/dictionary.txt
  docs/guides/security/ssl/how-to-secure-logstash-connections-using-ssl-certificates/index.md
Labels: wfl

#3996 [Update] How to Use Dockerfiles
  docs/guides/applications/containers/how-to-use-dockerfiles/index.md
Labels: SEO Improvements

#3234 add how to write vue plugin article
  docs/guides/development/javascript/how-to-write-vue-js-plugins/index.md
Labels: wfl

#3993 Initial draft of guide
  ci/vale/dictionary.txt
  docs/guides/development/concepts/what-is-unit-testing/index.md
Labels: est-ext

#3965 Introduction to FaaS
  ci/vale/dictionary.txt
  docs/guides/quick-answers/linux-essentials/introduction-to-function-as-a-service-faas/index.md
Labels: est-ext

#3318 [new] How to install python on Ubuntu, CentOS, and Debian
  ci/vale/dictionary.txt
  docs/guides/development/python/create-a-python-virtualenv-on-centos-8/index.md
  docs/guides/development/python/create-a-python-virtualenv-on-debian-10/index.md
  docs/guides/development/python/create-a-python-virtualenv-on-ubuntu-1610/index.md
  docs/guides/development/python/create-a-python-virtualenv-on-ubuntu-18-04/index.md
  docs/guides/development/python/how-to-install-python-on-centos-8/index.md
  docs/guides/development/python/how-to-install-python-on-debian-10/index.md
  docs/guides/development/python/how-to-install-python-on-ubuntu-20-04/index.md
Labels: wfl

#3367 [New] Manage python packages and virtual environments on Linux
  ci/vale/dictionary.txt
  docs/guides/development/python/how-to-manage-packages-and-virtual-enviroments-on-linux/index.md
Labels: wfl

#4036 [New] Self-Hosting the Password Manager bitwarden_rs Password Manager
  docs/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_browser_extension_login.png
  docs/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_create_account.png
  docs/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_login.png
  docs/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_signup_error.png
  docs/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_web_vault.png
  docs/guides/security/self-hosted-password-management-with-bitwarden-rs/index.md
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_browser_extension_login_hu1f75c8636e7ed0d0586036c3baed9372_26213_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_browser_extension_login_hu1f75c8636e7ed0d0586036c3baed9372_26213_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_browser_extension_login_hu1f75c8636e7ed0d0586036c3baed9372_26213_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_create_account_hu97484182c5b0a09b71ef7a8066240253_32255_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_create_account_hu97484182c5b0a09b71ef7a8066240253_32255_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_create_account_hucafcf8775721a4d5f9076f62667dd734_68461_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_create_account_hucafcf8775721a4d5f9076f62667dd734_68461_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_login_hu560c036efda62327774081f8eba4089b_35059_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_login_hu560c036efda62327774081f8eba4089b_35059_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_signup_error_hu76c30a90987e588cb80f8e54e32a088c_7718_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_rs_signup_error_hu76c30a90987e588cb80f8e54e32a088c_7718_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_web_vault_hu9f8a4696333df1962afd35b5d6646e2e_38495_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/self-hosted-password-management-with-bitwarden-rs/bitwarden_web_vault_hu9f8a4696333df1962afd35b5d6646e2e_38495_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: wfl

#4029 Yacht cyberpanel
  docs/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/cyberpanel-dashboard.png
  docs/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/index.md
  docs/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/log-into-cyberpanel.png
  docs/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/index.md
  docs/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-dashboard.png
  docs/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-demo.png
  docs/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-login.png
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/cyberpanel-dashboard_hu76c281dd9d1844078d5f1c2a0ac4010c_135_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/cyberpanel-dashboard_hu76c281dd9d1844078d5f1c2a0ac4010c_135_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/cyberpanel-dashboard_hu76c281dd9d1844078d5f1c2a0ac4010c_135_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/cyberpanel-dashboard_hueba8443f975ecbae106af4af39f73def_301708_2528x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/cyberpanel-dashboard_hueba8443f975ecbae106af4af39f73def_301708_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/cyberpanel-dashboard_hueba8443f975ecbae106af4af39f73def_301708_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/log-into-cyberpanel_hu04b31a9294e9a0b3d544b037d018906a_326254_2422x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-cyberpanel-with-marketplace-apps/log-into-cyberpanel_hu04b31a9294e9a0b3d544b037d018906a_326254_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-dashboard_hu1d66187b46911201caef1eb034ec2ae5_127766_2560x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-dashboard_hu1d66187b46911201caef1eb034ec2ae5_127766_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-dashboard_hu1d66187b46911201caef1eb034ec2ae5_127766_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-demo_hu7df3fef689a5fcbbb29ae08dab9b3921_403235_1946x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-demo_hu7df3fef689a5fcbbb29ae08dab9b3921_403235_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-login_hu355685695f145c9ecab115886aa4fda8_48365_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-yacht-with-marketplace-apps/yacht-login_hu355685695f145c9ecab115886aa4fda8_48365_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: marketplace

#4006 [New]NodeJS Marketplace App Guide
  ci/vale/dictionary.txt
  docs/guides/platform/marketplace/deploy-abberitnodejs-with-marketplace-apps/abberit-app-services-file-browser.png
  docs/guides/platform/marketplace/deploy-abberitnodejs-with-marketplace-apps/abberit-app-services-logs.png
  docs/guides/platform/marketplace/deploy-abberitnodejs-with-marketplace-apps/abberit-app-services-metrics.png
  docs/guides/platform/marketplace/deploy-abberitnodejs-with-marketplace-apps/index.md
  resources/_gen/images/guides/platform/marketplace/deploy-nodejs-with-marketplace-apps/abberit-app-services-file-browser_hu4d46981e3cc8a118ff0239d05fdfd605_44227_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-nodejs-with-marketplace-apps/abberit-app-services-file-browser_hu4d46981e3cc8a118ff0239d05fdfd605_44227_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-nodejs-with-marketplace-apps/abberit-app-services-file-browser_hu4d46981e3cc8a118ff0239d05fdfd605_44227_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-nodejs-with-marketplace-apps/abberit-app-services-logs_hud3000ed2e796d871bd9cf8f4ba464277_60280_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-nodejs-with-marketplace-apps/abberit-app-services-logs_hud3000ed2e796d871bd9cf8f4ba464277_60280_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-nodejs-with-marketplace-apps/abberit-app-services-metrics_hu36c60daec9ce44751545439a1cc3063e_42066_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/platform/marketplace/deploy-nodejs-with-marketplace-apps/abberit-app-services-metrics_hu36c60daec9ce44751545439a1cc3063e_42066_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: marketplace

#3906 [New] How to Deploy ServerWand with Marketplace Apps
  docs/guides/platform/marketplace/deploy-serverwand-with-marketplace-apps/accept-permissions.png
  docs/guides/platform/marketplace/deploy-serverwand-with-marketplace-apps/create-serverwand-server.png
  docs/guides/platform/marketplace/deploy-serverwand-with-marketplace-apps/index.md
Labels: Do Not Merge, marketplace

#3997 [New] Linux System Ports
  docs/guides/networking/diagnostics/check-linux-ports-in-use/index.md
Labels: est-ext

#4012 Update index.md for apache on CentOS 7
  docs/guides/web-servers/apache/install-and-configure-apache-on-centos-7/index.md
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/1461-SSH-Passphrase_huf6bd64d8edac3a8feb16510a7ced6cc8_16196_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/1461-SSH-Passphrase_huf6bd64d8edac3a8feb16510a7ced6cc8_16196_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/1461-SSH-Passphrase_huf6bd64d8edac3a8feb16510a7ced6cc8_16196_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-generate-key_huc84e4b5eebc8bc7c971e1053636a8593_10051_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-generate-key_huc84e4b5eebc8bc7c971e1053636a8593_10051_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-generating-key_hu057f14e6488e4712838064ec7bf6b2ec_9425_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-generating-key_hu057f14e6488e4712838064ec7bf6b2ec_9425_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-key-generated_hu4d11a1f8c9d993577877f3e3b4227b86_15999_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-key-generated_hu4d11a1f8c9d993577877f3e3b4227b86_15999_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-key-passphrase_hu9807e08b2c6ce14b185a829dba3fd74c_15771_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-key-passphrase_hu9807e08b2c6ce14b185a829dba3fd74c_15771_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-private-key-location_huc47b06dca4b191b973671cb326158b63_15170_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-private-key-location_huc47b06dca4b191b973671cb326158b63_15170_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-save-private-key_hu68e51681ba9eb17ed89b7f5af5d815ca_29325_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-save-private-key_hu68e51681ba9eb17ed89b7f5af5d815ca_29325_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-session-window_hu584542c1e5242f77d5bbdc4dcdc0097d_17064_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-session-window_hu584542c1e5242f77d5bbdc4dcdc0097d_17064_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-ssh-pubkey-in-notepad_hu6de262a32118ad6cce946d97dddc19f1_14422_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/putty-ssh-pubkey-in-notepad_hu6de262a32118ad6cce946d97dddc19f1_14422_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-my-keys_hu92100a61f53a28d734259f60c0704df6_52433_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-my-keys_hu92100a61f53a28d734259f60c0704df6_52433_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-my-profile_hue2a52678dc14cda8d768dcd660b1fa85_70997_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-my-profile_hue2a52678dc14cda8d768dcd660b1fa85_70997_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-new-key_hu16edec8fd6fbd4321c48817119c54719_81550_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-new-key_hu16edec8fd6fbd4321c48817119c54719_81550_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-new-linode_hu6d8b94e52cab539641b04b8307e3456b_60332_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/ssh-key-new-linode_hu6d8b94e52cab539641b04b8307e3456b_60332_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/use_public_key_authentication_with_ssh_hu1bb83e81d21fd121fd9a033c4541a893_234867_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/security/authentication/use-public-key-authentication-with-ssh/use_public_key_authentication_with_ssh_hu1bb83e81d21fd121fd9a033c4541a893_234867_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/nano-exit-save_hu8a2e0515121282cb5d050ee39ed944eb_5146_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/nano-exit-save_hu8a2e0515121282cb5d050ee39ed944eb_5146_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/nano-exit-save_hu8a2e0515121282cb5d050ee39ed944eb_5146_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/nano-find-replace_hu49a9492e88f6940a9bc8427e26171883_4078_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/nano-find-replace_hu49a9492e88f6940a9bc8427e26171883_4078_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/nano-new-buffer_hu5a013d3cfae2296274ab7d066e94d88c_6156_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/nano-new-buffer_hu5a013d3cfae2296274ab7d066e94d88c_6156_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/using_nano_smg_hu5f68290a0f014e7f8fd4fc0e6ebb8c87_502004_1388x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/use-nano-text-editor-commands/using_nano_smg_hu5f68290a0f014e7f8fd4fc0e6ebb8c87_502004_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: SEO Improvements

#3392 [New] Adds documentation for supervisord install on centos
  ci/vale/dictionary.txt
  docs/guides/tools-reference/tools/how-to-install-and-configure-supervisor-on-centos-8/index.md
  docs/guides/tools-reference/tools/how-to-install-and-configure-supervisor-on-centos-8/supervisor-web-interface.png
  resources/_gen/images/guides/tools-reference/tools/how-to-install-and-configure-supervisor-on-centos-8/supervisor-web-interface_hu023d2ee5747df7ce469d49b811e28b9f_84726_1748x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/how-to-install-and-configure-supervisor-on-centos-8/supervisor-web-interface_hu023d2ee5747df7ce469d49b811e28b9f_84726_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/how-to-install-and-configure-supervisor-on-centos-8/supervisor-web-interface_hu023d2ee5747df7ce469d49b811e28b9f_84726_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/setup-supervisor-on-centos/supervisor-web-interface_hu023d2ee5747df7ce469d49b811e28b9f_84726_1748x0_resize_q71_bgfafafc_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/setup-supervisor-on-centos/supervisor-web-interface_hu023d2ee5747df7ce469d49b811e28b9f_84726_640x0_resize_q75_bgffffff_catmullrom_2.jpg
  resources/_gen/images/guides/tools-reference/tools/setup-supervisor-on-centos/supervisor-web-interface_hu023d2ee5747df7ce469d49b811e28b9f_84726_694x0_resize_q71_bgfafafc_catmullrom_2.jpg
Labels: wfl

#3998 [New] YAML Syntax Reference
  ci/vale/dictionary.txt
  docs/guides/applications/configuration-management/basics/yaml-reference/index.md
Labels: est-ext
