Repository linode/docs, pull requests merged in 2024-10, with the labels that each got.

#7111 [New] Using OBJ with CDN guides
  docs/guides/platform/object-storage/optimizing-obj-bucket-architecture-for-akamai-cdn/Multi-bucket-arch1.png
  docs/guides/platform/object-storage/optimizing-obj-bucket-architecture-for-akamai-cdn/Multi-bucket-arch2.png
  docs/guides/platform/object-storage/optimizing-obj-bucket-architecture-for-akamai-cdn/Single-bucket-arch-level1.png
  docs/guides/platform/object-storage/optimizing-obj-bucket-architecture-for-akamai-cdn/Single-bucket-arch-level2.png
  docs/guides/platform/object-storage/optimizing-obj-bucket-architecture-for-akamai-cdn/index.md
  docs/guides/platform/object-storage/using-object-storage-with-akamai-cdn/CDN-Based-Architecture.png
  docs/guides/platform/object-storage/using-object-storage-with-akamai-cdn/DC-Based-Architecture.png
  docs/guides/platform/object-storage/using-object-storage-with-akamai-cdn/Edge-vs-DC-latency.png
  docs/guides/platform/object-storage/using-object-storage-with-akamai-cdn/index.md
Labels: Ready

#7121 [Updated] Preparing Infrastructure for High-Impact Advertising Traffic on Akamai
  docs/guides/akamai/solutions/preparing-infrastructure-for-high-impact-ad-traffic/high-impact-ad-traffic-arch-1.svg
  docs/guides/akamai/solutions/preparing-infrastructure-for-high-impact-ad-traffic/index.md
Labels: Ready

#7116 [New] Comparing Data Transfer Utilities
  ci/vale/dictionary.txt
  docs/contributors/leon-yen/_index.md
  docs/guides/tools-reference/file-transfer/comparing-data-transfer-utilities/index.md
Labels: Ready

#7125 Add Akamai Datasource Plugin To Prometheus/Grafana
  docs/marketplace-docs/guides/prometheus-grafana/grafana_akamai_ds.png
  docs/marketplace-docs/guides/prometheus-grafana/grafana_datasource4.png
  docs/marketplace-docs/guides/prometheus-grafana/index.md
Labels: Ready

#7129 [NEW] Migrating from Azure Functions to Knative
  docs/guides/kubernetes/migrating-from-aws-lambda-to-knative/index.md
  docs/guides/kubernetes/migrating-from-azure-functions-to-knative/Kubernetes-Dashboard-Get-Emojis-Azure.png
  docs/guides/kubernetes/migrating-from-azure-functions-to-knative/docker-hub-get-emojis-ts-repo.png
  docs/guides/kubernetes/migrating-from-azure-functions-to-knative/index.md
  docs/guides/kubernetes/migrating-from-azure-functions-to-knative/knative-azure-fuzz-emoji-result.jpg
  docs/guides/kubernetes/migrating-from-azure-functions-to-knative/knative-azure-get-emojis-ts-result.jpg
Labels: Ready

#7024 [NEW] Create a Realtime Data Stream with Apache Storm
  ci/vale/dictionary.txt
  docs/guides/applications/big-data/process-streams-in-realtime-with-apache-storm/index.md
  docs/guides/applications/big-data/process-streams-in-realtime-with-apache-storm/storm-flow.png
  docs/guides/applications/big-data/process-streams-in-realtime-with-apache-storm/storm-ui-wordcount-topology.png
  docs/guides/applications/big-data/process-streams-in-realtime-with-apache-storm/storm-ui.png
Labels: Ready

#6744 [update] Setting Up a Private Docker Registry with LKE and OBJ storage
  docs/guides/kubernetes/how-to-setup-a-private-docker-registry-with-lke-and-object-storage/index.md
Labels: Updated Guide, Ready

#6431 [New] How to Set up an Email Server using Postfix and Dovecot
  ci/vale/dictionary.txt
  docs/guides/email/postfix/how-to-setup-an-email-server/PostFixAdmin-Add-Mailbox.png
  docs/guides/email/postfix/how-to-setup-an-email-server/PostFixAdmin-New-Domain.png
  docs/guides/email/postfix/how-to-setup-an-email-server/PostFixAdmin-Setup-Page.png
  docs/guides/email/postfix/how-to-setup-an-email-server/PostFixAdmin-SuperAdmin-Creation-Page.png
  docs/guides/email/postfix/how-to-setup-an-email-server/index.md
Labels: New Guide, Ready
